# Automatically generated by configure - do not modify
SRC_PATH=/home/b7ack/x-fuzz/aflhier_pub/qemu_mode/qemu-3.1.1/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
